name: Node Matrix Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "Runnuing tests"
    steps:
   deploy:
     needs: test
     runs-on: ubantu-latest
     steps:
       - uses: actions/checkout@4
       - run: echo "Deploying to production" 
       
